  
title: textXchange
description: Textbook exchange service for the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-architect
github:
  is_project_page: true
  repository_url: https://github.com/textxchange/textxchange
gems:
